### ISSUE TITLE
Custom Seed Generator Doesn't Work for Steam Release

### ISSUE THREAD

**Issue by Scipo0419** [GhostTheBoo/custom-seed-generator#32]
I believe the issue lies in the hex values not matching what's in the Steam Release. I really just want to slightly buff the Ultima Weapon so it doesn't feel so bad to use it.

**Comment by GhostTheBoo** [comment]
Hey friend! Can you tell me what you changed for the Ultima Weapon? And how did you export the mod?

Fixing up the site to better work with Steam is on the radar but changing keyblade stats should definitely still work.

**Comment by Scipo0419** [comment]
I used the keyblade tab, changed the Strength and Magic stats to 7 and 4 respectively, ability to Combo Boost and replaced the vanilla Ultima Weapon. Saved it as a .lua file to load through the backend (which may be the problem), and started crashing when entering certain rooms (the usual spot in Twilight Town is the best place to test) game crashes on save file load as long as the script was in the folder.

**Comment by GhostTheBoo** [comment]
Great! So obviously not ideal that your game is crashing, but that is expected behavior.

What I suggest you do is export the mod as a zip file and install the mod that way in the mod manager. The Luas are definitely broken and I'm still trying to find the time to update the site to fix those. I'll let you know when those are good to go though.

**Comment by XxAkhilH47xX** [comment]
How do we export the mod as a .zip? Also, is there a specific GoA mod we're supposed to use? I've tested GoA ROM Edition 1.54.1 and it crashes as well.

**Comment by GhostTheBoo** [comment]
You can export the mod by going to the home page and clicking Save: ZIP. That should export a zip mod file that you can use in the mod manager directly.

I believe GoA support would be 1.53.5 but I'm not 100% sure on that. I'd have to do some additional testing on that. Though that compatibility is only for Lua mods. Zip mods should work regardless.

**Comment by XxAkhilH47xX** [comment]
Correct me if I'm wrong, but there doesn't appear to be a 'Save: ZIP' button on the home page, nor within the 'Save & Load' button.

![wtf](https://github.com/user-attachments/assets/0d08eb42-774d-4bb6-840b-321c595e420b)

**Comment by GhostTheBoo** [comment]
Lol ok that does explain a lot. Please use the following link moving forward as it supports ZIP seeds:
https://custom-seed-generator.web.app/

Out of curiosity, where did you get the link you were using? I see it on the repo itself and I'm gonna update that now. But wanna make sure everyone is using the correct page.

**Comment by XxAkhilH47xX** [comment]
Ahh, I see. Thank you very much for updating the link! 😄
I initially got the link from a mod description under Nexus, and since the repo pointed to the same link, I just assumed it was the updated one.

Much appreciated! 😉

**Comment by GhostTheBoo** [comment]
Link in README updated. Good callout!
